spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/wladlwe9t
    driver-class-name: org.postgresql.Driver
    username: wladlwe9t_user
    password: wladlwe9t_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port : 8080
  servlet:
    context-path: /api

security:
  user:
    name: tintin
    password: $2a$10$as6Pj2OayrIP/4x0ZrQlM.befOcqpZ9KtF73YTN3IYcGQ8rNsgYUS